name: Build and deploy dotnet core project to Azure Function App - swamplocksDbUpdater

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'AlphaVantage'  # Adjust the path if needed
  DOTNET_VERSION: '9.0.x' # Use your correct .NET version

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Resolve Project Dependencies Using Dotnet
        shell: bash
        run: |
          pushd './AlphaVantage'
          dotnet build --configuration Release --output ./output
          popd

      - name: Deploy to Azure Functions
        uses: azure/functions-action@v1
        with:
          app-name: 'swamplocksDbUpdater'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          publish-profile: ${{ secrets.AZURE_FUNCTION_PUBLISH_PROFILE }}
